# GitHub Pages configuration for Data Science for Kids
title: "Data Science for Kids Summer Camp"
description: "A magical 5-day journey into data science for kids!"
baseurl: "/data_science_for_kids"
url: "https://skysheng7.github.io"

# Theme and appearance
theme: minima
markdown: kramdown
highlighter: rouge

# Navigation structure
header_pages:
  - setup/index.md
  - day01/README.md
  - day02/README.md
  - day03/README.md
  - day04/README.md
  - day05/README.md
  - resources/index.md
  - instructor-guide/index.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - vendor/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/